### ISSUE TITLE
Raspberry Pi Imager 1.2 has been released

### ISSUE THREAD

**Issue by lurch** [popey/imager-snap#2]
I know nothing about snap packages, but looking at https://github.com/popey/imager-snap/blob/master/snap/gui/rpi-imager.desktop it seems you're still distributing `Version=1.0`? It would be nice if you could update to version 1.2: https://github.com/raspberrypi/rpi-imager/tree/v1.2

Also, would you mind adding a link to the [upstream repo](https://github.com/raspberrypi/rpi-imager) to your [README.md](https://github.com/popey/imager-snap/blob/master/README.md) ?

**Comment by popey** [comment]
Hi. No, that's not correct. The snap is current and up to date, and has been for a couple of weeks. The version string in the desktop file is no relation to the version number of the application. Note that the version stamp in the store is tagged 0264af9 which is the most recent commit to the upstream project. There's no work to do there. 

I have however, added a link to the upstream repo in the README.

**Comment by lurch** [comment]
Cool, thanks for the clarification :slightly_smiling_face: 
I also thought that you might be distributing an older version because the screenshot in the README doesn't show the version in the title-bar.

> Note that the version stamp in the store is tagged 0264af9

As already mentioned, I know nothing about snap packages. Just out of curiosity, how/where can I see that info?

**Comment by popey** [comment]
The screenshot was just taken before the 1.2 release.
If you visit the store page https://snapcraft.io/rpi-imager in the top right it shows 0264af9 which matches the most recent commit tag at https://github.com/raspberrypi/rpi-imager/commits/qml on the upstream project.

I'll likely change that to make it more obvious it's 1.2 though.

**Comment by popey** [comment]
I have modified the build so it uses the upstream version tagging, and updated the screenshots on the store page.
