### ISSUE TITLE
Missing library

### ISSUE THREAD

**Issue by marosg42** [popey/imager-snap#3]
Ubuntu 20.04 gnome edition, starting rpi-imager shows an error

`rpi-imager: error while loading shared libraries: libQt5Qml.so.5: cannot open shared object file: No such file or directory`

```
tracking:     latest/edge
refresh-date: today at 19:09 CEST
channels:
  latest/stable:    v1.2    2020-04-15 (28) 98MB -
  latest/candidate: ↑                            
  latest/beta:      v1.2    2020-04-15 (28) 98MB -
  latest/edge:      0264af9 2020-04-27 (33) 98MB -
installed:          0264af9            (33) 98MB -
```

**Comment by popey** [comment]
Thanks for the report. I can't see any difference between revision 33 (which you have) and revision 28. Yet 33 failed for you. I have triggered a rebuild anyway, and tested it. It works for me, on 20.04. Let me know how it goes for you.

**Comment by popey** [comment]
Can you also please try `snap remove rpi-imager` and `snap install rpi-imager` and see if that makes the issue go away.

**Comment by marosg42** [comment]
Found it, it was not the snap but broken .deb installation. Snap works fine. Thank you and sorry
